<!DOCTYPE html>
<html>

<head>
</head>

<body>

  <script>
    // async와 await를 사용하여 코드 변경하기
    // async function loadJson(url) {
    //   let response = await fetch(url);

    //   if (response.status == 200) {
    //     return await response.json();
    //     // Json도 프로미스를 반환하는걸로 추정된다, 그래서 답안 처럼 reponse.json()에 await를 붙이지 않으면, 바깥코드에서 기다려야 한다. 
    //   }
    //   throw new Error(response.status);

    // }

    // loadJson('no-such-user.json')
    //   .catch(alert); // Error: 404

    // async와 await를 사용해서 '다시 던지기' 예시 재작성하기 
    class HttpError extends Error {
      constructor(response) {
        super(`${response.status} for ${response.url}`);
        this.name = 'HttpError';
        this.response = response;
      }
    }

    async function loadJson(url) {
      let response = await fetch(url);
      if (response.status == 200) {
        return response.json();
      } else {
        throw new HttpError(response);
      }
    }

    // 유효한 사용자를 찾을 때까지 반복해서 username을 물어봄
    async function demoGithubUser() {

      let user;
      while (true) {
        let name = prompt("GitHub username을 입력하세요.", "iliakan");

        try {
          user = await loadJson(`https://api.github.com/users/${name}`);
          break; // 에러가 없으므로 반복문을 빠져나옵니다.
        } catch (err) {
          if (err instanceof HttpError && err.response.status == 404) {
            // 얼럿 창이 뜬 이후에 반복문은 계속 돕니다.
            alert("일치하는 사용자가 없습니다. 다시 입력해 주세요.");
          } else {
            // 알 수 없는 에러는 다시 던져집니다.
            throw err;
          }
        }
      }


      alert(`이름: ${user.name}.`);
      return user;
    }

    // demoGithubUser();
    //async가 아닌 함수에서 async 함수 호출하기
    async function wait() {
      await new Promise(resolve => setTimeout(resolve, 1000));

      return 10;
    }

    function f() {
      // ...코드...
      // async wait()를 호출하고 그 결과인 10을 얻을 때까지 기다리려면 어떻게 해야 할까요?
      // f는 일반 함수이기 때문에 여기선 'await'를 사용할 수 없다는 점에 주의하세요!
      wait().then(alert);
    }
    f();
  </script>


</body>

</html>